version: "3.6"

services:
    nginx:
        image: nginx:alpine
        container_name: arduino-nginx
        network_mode: host
        volumes: 
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./static/:/static/
        restart: unless-stopped
